const temas = [
  {
    id: "salvacao",
    titulo: "Plano de Salvação",
    descricao: "Compreendendo o plano divino para a redenção da humanidade",
    imagem: "/images/biblia.webp",
    categoria: "doutrina",
    versiculoChave: "João 3:16",
    disponivel: true,
  },
  {
    id: "fe",
    titulo: "Fé e Obras",
    descricao: "A relação entre a fé salvadora e as obras na vida cristã",
    imagem: "/images/biblia.webp",
    categoria: "vida-crista",
    versiculoChave: "Tiago 2:26",
    disponivel: true,
  },
  {
    id: "familia",
    titulo: "Família Cristã",
    descricao: "Princípios bíblicos para um lar que honra a Deus",
    imagem: "/images/biblia.webp",
    categoria: "relacionamentos",
    versiculoChave: "Efésios 5:21-6:4",
    disponivel: true,
  },
  {
    id: "oracao",
    titulo: "Poder da Oração",
    descricao: "Desenvolvendo uma vida de oração eficaz e transformadora",
    imagem: "/images/oração.jpg",
    categoria: "vida-crista",
    versiculoChave: "1 Tessalonicenses 5:17",
    disponivel: true,
  },
  {
    id: "espirito-santo",
    titulo: "Espírito Santo",
    descricao: "A pessoa e obra do Espírito Santo na vida do crente",
    imagem: "/images/espirito-santo.jpg",
    categoria: "doutrina",
    versiculoChave: "João 14:26",
    disponivel: true,
  },
  {
    id: "perda",
    titulo: "Lidando com Perdas",
    descricao: "Conforto bíblico em tempos de luto e dificuldades",
    imagem: "/images/biblia.webp",
    categoria: "vida-crista",
    versiculoChave: "Mateus 5:4",
    disponivel: true,
  },
  {
    id: "perdao",
    titulo: "Perdão e Reconciliação",
    descricao: "Superando mágoas e restaurando relacionamentos",
    imagem: "/images/biblia.webp",
    categoria: "relacionamentos",
    versiculoChave: "Mateus 6:14-15",
    disponivel: true,
  },
  {
    id: "apocalipse",
    titulo: "Escatologia Bíblica",
    descricao: "Estudo sobre os eventos finais e a volta de Cristo",
    imagem: "/images/leão.webp",
    categoria: "profetico",
    versiculoChave: "Apocalipse 1:7",
    disponivel: true,
  },
  {
    id: "tentacao",
    titulo: "Vencendo Tentações",
    descricao: "Estratégias bíblicas para resistir às tentações diárias",
    imagem: "/images/biblia.webp",
    categoria: "vida-crista",
    versiculoChave: "1 Coríntios 10:13",
    disponivel: true,
  },
  {
    id: "missoes",
    titulo: "Missões",
    descricao: "O chamado e a responsabilidade de compartilhar o evangelho",
    imagem: "/images/biblia.webp",
    categoria: "ministerio",
    versiculoChave: "Mateus 28:19-20",
    disponivel: true,
  },
  {
    id: "lideranca",
    titulo: "Liderança Servidora",
    descricao: "Princípios bíblicos para líderes que desejam impactar vidas",
    imagem: "/images/biblia.webp",
    categoria: "ministerio",
    versiculoChave: "Marcos 10:45",
    disponivel: true,
  },
  {
    id: "daniel",
    titulo: "Livro de Daniel",
    descricao: "Estudo profético sobre fidelidade em tempos de crise",
    imagem: "/images/leão.webp",
    categoria: "profetico",
    versiculoChave: "Daniel 2:44",
    disponivel: true,
  },
];
